In [12]:
# numpy 1 作业1，请对前文提到的Lotto程序进行三次运行，每次将结果存入列表，并确保第三次运行时所有结果以二维数组形式呈现为（3,6）的形状。
import numpy as np

all_results = [] # 存储三次运行结果的列表
# 运行三次程序
for i in range(3):
    np.random.seed(85 + i)  # 每次使用不同的种子，确保结果不同
    a = np.arange(1, 46)
    np.random.shuffle(a)
    lotto = a[:6]
    all_results.append(lotto)
    print(f'第{i+1}次运行结果: {lotto}')

# 将结果转换为(3,6)形状的二维数组
result_array = np.array(all_results)
print(f'\n所有结果组成的二维数组:')
print(result_array)
print(f'数组形状: {result_array.shape}')

第1次运行结果: [22  9 15 44 39 37]
第2次运行结果: [ 9 34 16 22  8 32]
第3次运行结果: [38 44 32  4  2 41]

所有结果组成的二维数组:
[[22  9 15 44 39 37]
 [ 9 34 16 22  8 32]
 [38 44 32  4  2 41]]
数组形状: (3, 6)


In [13]:
# numpy 2 作业2 请参考上述代码，完成下列要求，然后提供代码给我
# 1.创建形状数组（3,3,6），生成一个三维数组，元素的数值范围在0到20之间。2.创建形状数组（5,6），生成一个二维数组，元素为0到100之间的整数值
import numpy as np
shape_3d = (3, 3, 6) # 1. 创建形状为(3,3,6)的三维数组，元素数值范围在0到20之间
arr_3d = np.random.randint(0, 21, shape_3d)  # 注意：上限是21，因为randint的上限是开区间
print("三维数组 (3,3,6):")
print(arr_3d)
print(f"数组形状: {arr_3d.shape}\n")
shape_2d = (5, 6) # 2. 创建形状为(5,6)的二维数组，元素数值范围在0到100之间
arr_2d = np.random.randint(0, 101, shape_2d)  # 注意：上限是101，因为randint的上限是开区间
print("二维数组 (5,6):")
print(arr_2d)
print(f"数组形状: {arr_2d.shape}")

三维数组 (3,3,6):
[[[ 2 13  8 11  4 20]
  [ 6  8 13 16 12 17]
  [ 4  7 20 10  3  5]]

 [[ 9 12  2  9 20  1]
  [ 9 15 12 18 10  5]
  [ 4  0  3 20 12  8]]

 [[ 8 10  4 14  2 20]
  [ 6  0  8 11 19 11]
  [11  4  0 11 10  3]]]
数组形状: (3, 3, 6)

二维数组 (5,6):
[[70 35 17 31 90 69]
 [77 62 61 58 30  4]
 [27 20 46 46 65 90]
 [35  1 33 87 15 42]
 [23 25 14 76 95 20]]
数组形状: (5, 6)


In [14]:
# numpy 3 作业3创建一个由temp=np.arange（48）构成的一维数组temp，1.请使用reshape方法，创建一个随机生成的三维数组（4,3,4）和二维数组（6,8）
import numpy as np
temp = np.arange(48) # 创建由0到47的一维数组
print(temp)
arr_3d = temp.reshape(4, 3, 4) # 1. 使用reshape()方法创建三维数组(4,3,4)
print("重塑后的三维数组 (4,3,4):")
print(arr_3d)
print(f"三维数组形状: {arr_3d.shape}\n")
arr_2d = temp.reshape(6, 8) # 2. 使用reshape()方法创建二维数组(6,8)
print("重塑后的二维数组 (6,8):")
print(arr_2d)
print(f"二维数组形状: {arr_2d.shape}")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
重塑后的三维数组 (4,3,4):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
三维数组形状: (4, 3, 4)

重塑后的二维数组 (6,8):
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]
二维数组形状: (6, 8)
